name: Package with RubyGems
on: {release: {types: [published]}}
jobs:
  package:
    runs-on: windows-latest
    timeout-minutes: 5
    steps:
    
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - uses: ruby/setup-ruby@v1
      with:
        windows-toolchain: 'none'
        ruby-version: '3'
    
    - name: Package Gem
      run: gem build --output .gem *.gemspec
    
    - name: Publish to RubyGems
      run: gem push .gem
      env:
        GEM_HOST_API_KEY: ${{ secrets.GEM_HOST_API_KEY }}
