name: Check Types with Steep
on:
  push:
    paths: [.github/workflows/type_check.yml, lib/**, Gemfile, '*.gemspec']
  pull_request:
    paths: [.github/workflows/type_check.yml, lib/**, Gemfile, '*.gemspec']
jobs:
  
  type_check:
    runs-on: windows-latest
    timeout-minutes: 5
    steps:

    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3'
        bundler-cache: true
    
    - name: Check Types with Steep
      run: bundle exec steep check
